hours = input("Enter your hours of work: ")
rate = input("Enter your rate: ")
pay = float(hours) * float(rate)
print('Your pay is: ' + str(pay))
print('All payment of' + str(pay) +'is made via wire transfer')
print('your working hour is'+ str(hours))